[project]
name = "citi-bike-forecaster"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "code4ry", email = "140927679+code4ry@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.142.2",
    "httpx>=0.28.1",
    "pandas>=3.0.6",
    "psycopg[binary]>=3.3.6",
    "pydantic-settings>=2.15.0",
    "scikit-learn>=1.9.1",
    "sqlalchemy>=2.1.3",
    "xgboost-cpu>=3.4.1",
]

[project.scripts]
citi-bike-forecaster = "citi_bike_forecaster:main"

[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]
